"""Centralized application error codes."""

AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
EMAIL_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
INVALID_TOKEN = "INVALID_TOKEN"
TOKEN_EXPIRED = "TOKEN_EXPIRED"
USER_NOT_FOUND = "USER_NOT_FOUND"
VALIDATION_ERROR = "VALIDATION_ERROR"

